# Generated by Django 3.0.7 on 2020-06-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdhuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdhuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
